[FileDialog]
history=file:///home/main/hw2255/cmpe-260/lab/lab3/report, file:///home/main/hw2255/cmpe-260/lab/lab3/report/deliverables, file:///home/main/hw2255/eeee-281/lab/lab2/report, file:///home/main/hw2255/cmpe-250/lab/lab8/report, file:///home/main/hw2255/cmpe-250/lab/lab8/report/assets, file:///home/main/hw2255/cmpe-250/lab/lab8/report/deliverables
lastVisited=file:///home/main/hw2255/cmpe-250/lab/lab8/report/deliverables
qtVersion=6.11.0
shortcuts=file:, file:///home/main, file:///home/main/hw2255
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
